# Generated by Django 4.1.7 on 2023-03-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_email_alter_patient_age_alter_patient_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='São Paulo', max_length=100),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='default_value', max_length=100),
        ),
    ]
